export const PRODUCTS_RECEIVED = "PRODUCTS_RECEIVED";
export const ADD_TO_CART = "ADD_TO_CART";
export const CALCULATE_TOTAL = "CALCULATE_TOTAL";

export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
